import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Link from "next/link";

export async function getStaticProps() {
  const data = await fetch("https://jsonplaceholder.typicode.com/todos");
  const todos = await data.json();

  return {
    props: {
      data: todos,
    },
  };
}

export default function Home(props) {
  console.log(props);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>todos</h1>

      <ul>
        {props.data.map((u) => (
          <li className={styles.red} key={u.id}>
            <Link href={`todos/${u.id}`}>
              <a>
                {u.id} - Title:
                {u.title}
              </a>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}
